evo add testing translation
forresst/nodebestpractices pull request #11
Opened 2021-01-01 22:58 UTC by tkhadir

init testing part  french translation

2021-01-02 19:38 UTC, forresst commented on README.french.md
> +4. [Test et qualitée globale (12) ](#4-test-et-qualitée-globale)
Euh, non "la qualité" s'écrit sans e : https://fr.wikipedia.org/wiki/Qualit%C3%A9

2021-01-02 19:58 UTC, tkhadir commented on README.french.md
> +4. [Test et qualitée globale (12) ](#4-test-et-qualitée-globale)
bonne remarque c'est corrigé :)  je soumettrais le reste au fur et à mesure merci 👍

2021-01-04 10:38 UTC, forresst requested changes
Merci pour ton excellent travail, même si j'ai beaucoup de remarques, ton travail est superbe.
J'ai juste proposer plusieurs modifications pour être raccord avec ce qui a déjà été traduit.

Une remarque, il faut en français rajouté un espace avant un ":" : j'ai proposée à chaque fois une modif dans ce sens

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +# `4. Test et qualitée globale`
Même remarque qualité sans e

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** La plupart des projets n'ont tout simplement pas de test automatisé en raison de délais courts ou souvent le «projet de test» est devenu incontrôlable et a été abandonné. Pour cette raison
```suggestion
**TL;PL :** La plupart des projets n'ont tout simplement pas de test automatisé en raison de délais courts ou souvent le « projet de test » est devenu incontrôlable et a été abandonné. Pour cette raison, priorisez et commencez par les tests d'API, qui est le moyen le plus simple d'écrire et qui offre plus de couverture que les tests unitaires (vous pouvez même créer des tests d'API sans code à l'aide d'outils comme [Postman](https://www.getpostman.com/) Par la suite, si vous avez plus de ressources et de temps, continuez avec des types de tests avancés tels que les tests unitaires, les tests DB (base de données), les tests de performances, etc.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Vous pouvez passer de longues journées à écrire des tests unitaires pour découvrir que vous n'avez qu'une couverture système de 20%
```suggestion
**Autrement :** Vous pouvez passer de longues journées à écrire des tests unitaires pour découvrir que vous n'avez qu'une couverture système de 20%
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Faites en sorte que le test parle au niveau des exigences afin qu'il soit explicite également pour les ingénieurs et développeurs QA qui ne sont pas familiarisés avec les internes du code.
```suggestion
**TL;PL :** Donnez un nom de test éloquent selon son niveau d'exigences pour qu'il soit compréhensible par les ingénieurs et développeurs de l'assurance qualité qui ne sont pas familiers avec les codes internes. Indiquez dans le nom du test ce qui est testé (élément du test), dans quelles circonstances et quel est le résultat attendu.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Un déploiement vient d'échouer, un test nommé «Ajouter un produit» a échoué. Cela vous indique-t-il exactement ce qui fonctionne mal?
```suggestion
**Autrement :** Un déploiement vient d'échouer, un test nommé « Ajoute un produit » a échoué. Cela vous indique-t-il exactement ce qui ne fonctionne pas correctement ?
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +# `4. Test et qualité globale`
```suggestion
# `4. Tests et pratiques générales de qualité`
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.2 Inclure 3 parties dans chaque nom de test
```suggestion
## ![✔] 4.2 Incluez 3 parties dans chaque nom de test
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.3 Tests de structure en utilisant le motif AAA
```suggestion
## ![✔] 4.3 Structurez vos tests avec le format AAA
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Structurez vos tests avec 3 sections bien séparées: Arrange, Act & Assert (AAA). La première partie comprend la configuration du test, puis l'exécution de l'unité sous test et enfin la pha
```suggestion
**TL;PL :** Structurez vos tests avec 3 sections bien séparées : Arrange, Act & Assert (AAA). La première partie comprend la configuration du test, puis l'exécution de l'unité testée et enfin la phase d'assertion (vérification). Le respect de cette structure garantit que le lecteur n'utilise pas de le CPU de son cerveau pour comprendre le plan de test.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Non seulement vous passez de longues heures par jour à comprendre le code principal, mais maintenant ce qui aurait dû être la partie la plus simple de la journée (test) étire votre cerveau
```suggestion
**Autrement :** Non seulement vous passez de longues heures par jour à comprendre le code principal, mais maintenant, ce qui aurait dû être la partie la plus simple de la journée (les tests) accroche votre cerveau
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +🔗[**Plus d'infos: Incluez 3 parties dans chaque nom de test**](/sections/testingandquality/3-parts-in-name.french.md)
```suggestion
🔗[**Plus d'infos : Incluez 3 parties dans chaque nom de test**](/sections/testingandquality/3-parts-in-name.french.md)
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +🔗[**Plus d'infos: Structurez vos tests avec le format AAA**](/sections/testingandquality/aaa.french.md)
```suggestion
🔗[**Plus d'infos : Structurez vos tests avec le format AAA**](/sections/testingandquality/aaa.french.md)
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.4 Détecter les problèmes de code avec un linter
```suggestion
## ![✔] 4.4 Détectez les problèmes de code avec un linter
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Utilisez un linter de code pour vérifier la qualité de base et détecter les anti-modèles tôt. Exécutez-le avant tout test et ajoutez-le en tant que git-hook pré-commit pour minimiser le te
```suggestion
**TL;PL :** Utilisez un linter de code pour vérifier la qualité et détecter les antipatterns au plus tôt. Exécutez-le avant les tests et ajoutez-le en tant que git-hook de pré-commit pour diminuer le temps nécessaire pour examiner et corriger tout problème. Vérifiez également la [section 3](#3-style-du-code) sur les pratiques de style de code.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Vous pouvez laisser passer un anti-pattern et un éventuel code vulnérable à votre environnement de production.
```suggestion
**Autrement :** Vous pouvez laisser passer un code antipatterns et éventuellement vulnérable sur votre environnement de production.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.5 Évitez les montages de test globaux et les semences, ajoutez des données par test
```suggestion
## ![✔] 4.5 Évitez les tests globaux, ajoutez des données pour chaque test
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL; DR:** Pour éviter le couplage des tests et raisonner facilement sur le flux de test, chaque test doit ajouter et agir sur son propre ensemble de lignes BDD. Chaque fois qu'un test doit extraire
```suggestion
**TL;PL :** Pour éviter le chevauchement des tests et expliquer facilement le déroulement du test, chaque test doit ajouter et agir sur son propre ensemble d'enregistrement de la base de données. Chaque fois qu'un test a besoin de récupérer ou de présumer l'existence de certaines données de la BD - il doit explicitement ajouter ces données et éviter de modifier tout autre enregistrement.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Considérez un scénario où le déploiement est interrompu en raison d'échecs de tests, l'équipe va maintenant passer un temps précieux d'investigation qui se termine par une triste conclusio
```suggestion
****Autrement :** Considérez un scénario où le déploiement est interrompu à cause de l'échec des tests, l'équipe va maintenant passer un temps d'investigation précieux qui se terminera par une triste conclusion : le système fonctionne bien, les tests interfèrent cependant les uns avec les autres et interrompent la construction.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.6 Inspecter en permanence les dépendances vulnérables
```suggestion
## ![✔] 4.6 Inspectez en permanence les dépendances vulnérables
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +🔗[**Plus d'infos: Évitez les tests globaux, ajoutez des données pour chaque test**](/sections/testingandquality/avoid-global-test-fixture.french.md)
```suggestion
🔗[**Plus d'infos : Évitez les tests globaux, ajoutez des données pour chaque test**](/sections/testingandquality/avoid-global-test-fixture.french.md)
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Même les dépendances les plus réputées telles qu'Express ont des vulnérabilités connues. Cela peut être facilement apprivoisé en utilisant des outils communautaires et commerciaux tels que
```suggestion
**TL;PL :** Même les dépendances les plus réputées telles qu'Express ont des vulnérabilités connues. Cela peut être facilement apprivoisé à l'aide d'outils communautaires et commerciaux tels que 🔗 [npm audit](https://docs.npmjs.com/cli/audit) et 🔗 [snyk.io](https://snyk.io) qui peuvent être appelé depuis votre CI pour chaque construction.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Garder votre code propre des vulnérabilités sans outils dédiés nécessitera de suivre en permanence les publications en ligne sur les nouvelles menaces. Assez fastidieux
```suggestion
**Autrement :** Garder votre code propre contre les vulnérabilités sans outils dédiés nécessitera de suivre en permanence les publications en ligne sur les nouvelles menaces. C'est assez fastidieux.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.7 Marquer vos tests
```suggestion
## ![✔] 4.7 Étiquetez vos tests
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Différents tests doivent s'exécuter sur différents scénarios: fumée rapide, sans IO, les tests doivent être exécutés lorsqu'un développeur enregistre ou valide un fichier, les tests comple
```suggestion
**TL;PL :** Différents tests doivent s'exécuter selon différents scénarios : test d'intégrité, sans IO, les tests doivent s'exécuter lorsqu'un développeur enregistre ou commit un fichier, les tests complets de bout en bout s'exécutent généralement lorsqu'une nouvelle « pull request » est soumise, etc. Cela peut être réalisé en étiquetant les tests avec des mots clés comme #IO #api #integrite afin que vous puissiez utiliser votre harnais de test et invoquer le sous-ensemble souhaité. Par exemple, voici comment vous invoqueriez uniquement le groupe de test d'intégrité avec [Mocha](https://mochajs.org/) :
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** L'exécution de tous les tests, y compris des tests qui exécutent des dizaines de requêtes DB (base de données), chaque fois qu'un développeur apporte un petit changement peut être extrêmem
```suggestion
**Autrement :** Exécutez tous les tests, y compris les tests qui effectuent des dizaines de requêtes sur la base de données, chaque fois qu'un développeur apporte un petit changement, cela peut être extrêmement lent et souvent les développeurs s'abstiennent de faire des tests.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.8 Vérifiez votre couverture de test, cela aide à identifier les mauvais modèles de test
```suggestion
## ![✔] 4.8 Vérifiez votre couverture de test, cela aide à identifier les mauvaises conception de test
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Les outils de couverture de code comme [Istanbul](https://github.com/istanbuljs/istanbuljs) / [NYC](https://github.com/istanbuljs/nyc) sont parfaits pour 3 raisons : il est gratuit (aucun
```suggestion
**TL;PL :** Les outils de couverture de code comme [Istanbul](https://github.com/istanbuljs/istanbuljs)/[NYC](https://github.com/istanbuljs/nyc) sont parfaits pour 3 raisons : ils sont gratuits (aucun effort n'est nécessaire pour bénéficier de ces rapports), ils aident à identifier une diminution de la couverture des tests, et enfin et surtout, ils mettent en évidence les incompatibilités de test : en regardant les rapports de couverture de code en couleur, vous remarquerez peut-être, par exemple, des zones de code qui ne sont jamais testées comme les clauses catch (ce qui signifie que les tests invoquent uniquement les chemins positifs et non le comportement de l'application en cas d'erreur). Configurez-les pour faire échouer les constructions si la couverture tombe sous un certain seuil.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Aucune métrique automatique ne vous indiquera lorsqu'une grande partie de votre code n'est pas couverte par les tests
```suggestion
**Autrement :** Il n'y aura aucune mesure automatisée vous indiquant quand une grande partie de votre code n'est pas couverte par les tests
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.9 Inspecter les paquets obsolètes
```suggestion
## ![✔] 4.9 Inspectez les paquets obsolètes
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Utilisez votre outil préféré (par exemple «npm obsolète» ou [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) pour détecter les packages installés qui sont obsolètes, in
```suggestion
**TL;PL :** Utilisez votre outil préféré (par exemple, « npm outdated » ou [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) pour détecter les paquets installés qui sont obsolètes, injectez cette vérification dans votre CI et même faites échouer une construction dans un scénario critique. Par exemple, un scénario critique peut se produire lorsqu'un paquet installé a 5 patchs de retard (par exemple, la version locale est 1.3.1 et la version du référentiel est 1.3.8) ou quand il est marqué comme obsolète par son auteur - stoppez la construction et empêchez le déploiement de cette version.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Votre production exécutera des packages qui ont été explicitement étiquetés par leur auteur comme risqués
```suggestion
**Autrement :** Votre production exécutera des paquets qui ont été explicitement étiquetés par leur auteur comme risqués.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.10 Utiliser un environnement de type pre-production pour les tests e2e
```suggestion
## ![✔] 4.10 Utilisez pour les tests e2e un environnement proche de la production
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Les tests de bout en bout (e2e) qui incluent des données en direct étaient le maillon le plus faible du processus CI car il dépend de plusieurs services lourds comme DB (la base données).
```suggestion
**TL;PL :** Les tests de bout en bout (e2e) qui comprennent l'utilisation de données en direct sont les maillons les plus faibles du processus du CI car ils dépendent de plusieurs services complexes comme la base de données. Utilisez un environnement de test continue aussi proche que possible de votre production actuelle.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Sans docker-compose, les équipes doivent conserver une base de données de test pour chaque environnement de test, y compris les machines des développeurs, garder toutes ces bases de donnée
```suggestion
**Autrement :** Sans docker-compose, les équipes doivent maintenir une base de données de test pour chaque environnement de test, y compris les machines des développeurs, garder toutes ces bases de données synchronisées afin que les résultats des tests ne varient pas d'un environnement à l'autre.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +## ![✔] 4.11 Refactoriser régulièrement à l'aide d'outils d'analyse statique
```suggestion
## ![✔] 4.11 Refactorisez régulièrement à l'aide d'outils d'analyse statique
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** L'utilisation d'outils d'analyse statique aide en donnant des moyens objectifs d'améliorer la qualité du code et de maintenir votre code maintenable. Vous pouvez ajouter des outils d'analy
```suggestion
**TL;PL :** L'utilisation d'outils d'analyse statique vous aide en donnant des moyens concrets d'améliorer la qualité du code et permet de maintenir votre code. Vous pouvez ajouter des outils d'analyse statique à votre CI pour échouer lorsqu'il trouve du code incorrect. Ses principaux arguments de vente par rapport au contrôle ordinaire de code sont la capacité d'inspecter la qualité dans le contexte de plusieurs fichiers (par exemple, détecter les doublons), d'effectuer une analyse avancée (par exemple la complexité du code) et de suivre l'historique et la progression des problèmes de code. Deux exemples d'outils que vous pouvez utiliser sont [Sonarqube](https://www.sonarqube.org/) (+ de 2 600 [étoiles](https://github.com/SonarSource/sonarqube)) et [Code Climate](https://codeclimate.com/) (+ de 1 500 [étoiles](https://github.com/codeclimate/codeclimate)).
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Avec une qualité de code médiocre, les bogues et les performances seront toujours un problème qu'aucune nouvelle bibliothèque brillante ou fonctionnalités de pointe ne peuvent résoudre
```suggestion
**Autrement :** Avec une mauvaise qualité de code, les bogues et les performances seront toujours un problème qu'aucune nouvelle bibliothèque brillante ou fonctionnalité de pointe ne peut résoudre.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**TL;DR:** Votre plate-forme d'intégration continue (CICD) hébergera tous les outils de qualité (par exemple, test, peluche), elle devrait donc être accompagnée d'un écosystème dynamique de plugins.
```suggestion
**TL;PL :** Votre plateforme d'intégration continue (CICD) hébergera tous les outils de qualité (par exemple test, lint), elle devrait donc être accompagnée d'un écosystème dynamique de plugins. [Jenkins](https://jenkins.io/) était utilisé par défaut pour de nombreux projets car il a la plus grande communauté avec une plateforme très puissante au prix d'une configuration complexe qui nécessite une courbe d'apprentissage abrupte. De nos jours, il est devenu beaucoup plus facile de mettre en place une solution CI en utilisant des outils SaaS comme [CircleCI](https://circleci.com) et d'autres. Ces outils permettent de créer un pipeline de CI flexible sans avoir à gérer l'ensemble de l'infrastructure. Finalement, c'est un compromis entre robustesse et rapidité - choisissez votre camp avec soin.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +**Sinon:** Le choix d'un fournisseur de niche pourrait vous bloquer une fois que vous aurez besoin d'une personnalisation avancée. D'un autre côté, utiliser Jenkins pourrait faire perdre un temps pré
```suggestion
**Autrement :** Le choix d'un fournisseur de niche peut vous bloquer une fois que vous aurez besoin d'une personnalisation avancée. En revanche, faire appel à Jenkins pourrait vous faire perdre un temps précieux à la mise en place de l'infrastructure.
```

2021-01-04 10:38 UTC, forresst commented on README.french.md
> +🔗[**Plus d'infos: Choisissez soigneusement votre plateforme CI**](/sections/testingandquality/citools.french.md)
```suggestion
🔗[**Plus d'infos : Choisissez soigneusement votre plateforme CI**](/sections/testingandquality/citools.french.md)
```

2021-01-06 21:04 UTC, tkhadir commented
Hello @forresst merci beaucoup pour la relecture, je pense qu'on est bon pour cette partie, n'hésites à pas à revenir vers moi si besoin 👍

2021-01-07 07:54 UTC, forresst approved these changes

2021-01-07 07:54 UTC, merged

2021-01-07 07:55 UTC, forresst commented
@tkhadir Merci pour ton superbe travail