French translation
forresst/nodebestpractices pull request #2
Opened 2019-12-31 01:46 UTC by MrYamous

Translate avoid_publishing_secrets (9c5e1e7) & avoideval (a4d604a) files

2020-01-02 17:49 UTC, forresst requested changes
Avant tout merci pour ton aide.

Quelques remarques et corrections, je reste à ta disposition pour en discuter si besoin

2020-01-02 17:49 UTC, forresst commented on sections/security/avoid_publishing_secrets.french.md
> +Il est important de noter que si un projet utilise à la fois des fichiers `.npmignore` et `.gitignore`, tout ce qui n'est pas dans `.npmignore` est publié dans le registre (i.e. le fichier `.npmignor
```suggestion
Il est important de noter que si un projet utilise à la fois des fichiers `.npmignore` et `.gitignore`, tout ce qui n'est pas dans `.npmignore` est publié dans le registre (c'est-à-dire que le fichier `.npmignore` écrase `.gitignore`). Cette condition est communément une source de confusion et un problème qui peut mener à la fuite de secrets. Les développeurs ont l'habitude de mettre à jour le fichier `.gitignore`, mais peuvent oublier de faire de même avec `.npmignore`, ce qui peut conduire à ce qu'un potentiel fichier sensible ne soit pas envoyé sur l'outil de gestion des versions, mais soit toujours inclus dans le package npm.
```

i.e. => c'est-à-dire que

2020-01-02 17:49 UTC, forresst commented on sections/security/avoid_publishing_secrets.french.md
> +# Éviter de publier les secrets dans le registre npm
```suggestion
# Éviter de publier les secrets dans le registre npm
```

2020-01-02 17:49 UTC, forresst commented on sections/security/avoid_publishing_secrets.french.md
> +Par [Liran Tal & Juan Picado sur Snyk](https://snyk.io/blog/ten-npm-security-best-practices/):
```suggestion
Extrait du blog de [Liran Tal & Juan Picado sur Snyk](https://snyk.io/blog/ten-npm-security-best-practices/):
```
Juste pour être en accord avec les autres traductions

2020-01-02 17:49 UTC, forresst commented on sections/security/avoid_publishing_secrets.french.md
> +> ... Une autre bonne pratique à adopter est d'utiliser la propriété files du package.json, qui fonctionne comme une liste blanche et spécifie un tableau de fichiers à inclure dans le package qui ser
```suggestion
> ... Une autre bonne pratique à adopter est d'utiliser la propriété files du package.json, qui fonctionne comme une liste blanche et spécifie un tableau de fichiers à inclure dans le package qui sera créé et installé (tandis que le fichier .npmignore fonctionne comme une liste noire). La propriété files et le fichier .npmignore peuvent être utilisés ensemble pour déterminer explicitement quels fichiers doivent être inclus, et exclus, du package. Quand les deux sont utilisés, la propriété files du package.json a la priorité sur le fichier .npmignore.
```
crée => créé

2020-01-02 17:49 UTC, forresst commented on sections/security/avoid_publishing_secrets.french.md
> +Sur le [blog de npm](https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish)
```suggestion
Extrait du [blog de npm](https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish)
```

2020-01-02 17:49 UTC, forresst commented on sections/security/avoideval.french.md
> +Du livre « Essential Node.js Security » de [Liran Tal](https://leanpub.com/nodejssecurity):
```suggestion
Extrait du livre « Essential Node.js Security » de [Liran Tal](https://leanpub.com/nodejssecurity):
```

2020-01-03 21:55 UTC, MrYamous commented on sections/security/avoid_publishing_secrets.french.md
> +Il est important de noter que si un projet utilise à la fois des fichiers `.npmignore` et `.gitignore`, tout ce qui n'est pas dans `.npmignore` est publié dans le registre (i.e. le fichier `.npmignor
Ça me semblait acceptable de garder i.e. même en français, mais après recherche c'est un anglicisme alors je te rejoins sans soucis. Bien vu du coup

2020-01-04 08:40 UTC, forresst approved these changes

2020-01-04 08:44 UTC, merged

2020-01-04 08:50 UTC, forresst commented
@MrYamous J'ai intégré ta PR dans la branche french-translation.

Merci encore pour ton travail de qualité.