Translation of `createmaintenanceendpoint.md`
forresst/nodebestpractices pull request #5
Opened 2020-01-10 09:47 UTC by forresst

2020-01-10 10:20 UTC, forresst commented
@MrYamous Si tu as un peu de temps pour relire ma traduction

2020-01-10 16:04 UTC, MrYamous requested changes

2020-01-10 16:04 UTC, MrYamous commented on sections/production/createmaintenanceendpoint.french.md
> +Un point de terminaison de maintenance est une API HTTP hautement sécurisée qui fait partie du code de l'application et dont son objectif est d'être utilisé par l'équipe d'exploitation/production pou
```suggestion
Un point de terminaison de maintenance est une API HTTP hautement sécurisée qui fait partie du code de l'application et dont l'objectif est d'être utilisé par l'équipe d'exploitation/production pour surveiller et exposer les fonctionnalités de maintenance. Par exemple, il peut retourner un vidage de mémoire (instantané de la mémoire) du processus, signaler s'il y a des fuites de mémoire et même permettre d'exécuter directement des commandes REPL. Ce point de terminaison est nécessaire lorsque les outils DevOps classiques (produits de surveillance, journaux, etc.) ne parviennent pas à collecter un certain type d'informations spécifiques ou si vous choisissez de ne pas acheter/installer de tels outils. La règle d'or est d'utiliser des outils professionnels et externes pour le suivi et la maintenance de la production, ceux-ci sont généralement plus robustes et plus précis. Cela dit, il est probable que les outils génériques ne parviennent pas à extraire des informations spécifiques de Node ou de votre application - par exemple, si vous souhaitez générer un instantané de mémoire au moment où le GC a terminé un cycle - quelques bibliothèques npm se feront un plaisir de vous le faire, mais les outils de surveillance populaires manqueront probablement cette fonctionnalité. Il est important de garder ce point de terminaison privé et accessible uniquement par les administrateurs, car il peut devenir la cible d'une attaque DDOS.
```

- dont son objectif --> dont l'objectif

Remarque - "the moment GC completed a cycle" 
Peut-être définir GC, dans le cadre où ce document pourrait être amené à être lu par des personnes qui ont différentes expériences, plus au moins conséquences, il pourrait ne pas être parlant pour tous et toutes.

2020-01-10 16:04 UTC, MrYamous commented on sections/production/createmaintenanceendpoint.french.md
> +[Préparez la production de votre application Node.js (Slides)](http://naugtur.pl/pres3/node2prod)
```suggestion
[Préparez votre application Node.js pour la production (Slides)](http://naugtur.pl/pres3/node2prod)
```

2020-01-10 16:04 UTC, MrYamous commented on sections/production/createmaintenanceendpoint.french.md
> +▶ [Préparez la production de votre application Node.js (Video)](https://www.youtube.com/watch?v=lUsNne-_VIk)
```suggestion
▶ [Préparez votre application Node.js pour la production (Video)](https://www.youtube.com/watch?v=lUsNne-_VIk)
```

2020-01-10 16:04 UTC, MrYamous commented on sections/production/createmaintenanceendpoint.french.md
> +![Préparez la production de votre application Node.js](/assets/images/createmaintenanceendpoint1.png "Préparez la production de votre application Node.js")
```suggestion
![Préparez votre application Node.js pour la production](/assets/images/createmaintenanceendpoint1.png "Préparez votre application Node.js pour la production")
```

2020-01-10 16:35 UTC, forresst commented on sections/production/createmaintenanceendpoint.french.md
> +Un point de terminaison de maintenance est une API HTTP hautement sécurisée qui fait partie du code de l'application et dont son objectif est d'être utilisé par l'équipe d'exploitation/production pou
@MrYamous Oui tu as raison GC n'est pas parlant, je pense donc mettre ceci:

```markdown
où le GC (Garbage collection, NdT : [« Ramasse-miettes »](https://fr.wikipedia.org/wiki/Ramasse-miettes_(informatique))) a terminé un cycle
```

Avec le lien wikipedia en plus, qu'en penses tu ?

2020-01-11 15:44 UTC, MrYamous commented on sections/production/createmaintenanceendpoint.french.md
> +Un point de terminaison de maintenance est une API HTTP hautement sécurisée qui fait partie du code de l'application et dont son objectif est d'être utilisé par l'équipe d'exploitation/production pou
Ça me semble plus clair de cette manière

2020-01-11 15:46 UTC, MrYamous approved these changes

2020-01-12 08:11 UTC, merged