Translation of 'productioncode.md'
forresst/nodebestpractices pull request #7
Opened 2020-01-12 08:45 UTC by forresst

2020-01-12 08:46 UTC, forresst commented
@MrYamous Si tu passes dans le coin 😃 Merci

2020-01-15 08:22 UTC, MrYamous requested changes

2020-01-15 08:22 UTC, MrYamous commented on sections/production/productioncode.french.md
> +* Soyez sans état – Enregistrez aucune donnée localement sur un serveur web spécifique (consultez le point – « Soyez sans état »)
```suggestion
* Soyez sans état – N'enregistrez aucune donnée localement sur un serveur web spécifique (consultez le point – « Soyez sans état »)
```

2020-01-15 08:22 UTC, MrYamous commented on sections/production/productioncode.french.md
> +* Testez la mémoire – Mesurer l'utilisation de la mémoire et les fuites dans le cadre de votre flux de développement, des outils tels que « memwatch » peuvent grandement faciliter cette tâche
```suggestion
* Testez la mémoire – Mesurez l'utilisation de la mémoire et les fuites dans le cadre de votre flux de développement, des outils tels que « memwatch » peuvent grandement faciliter cette tâche
```

2020-01-15 12:54 UTC, MrYamous approved these changes

2020-02-06 09:15 UTC, merged