Translate childprocesses
forresst/nodebestpractices pull request #9
Opened 2020-02-02 22:27 UTC by MrYamous

@forresst Quand tu passes dans le coin ;) 

J'ai notamment un doute sur la traduction de sanitize, c'est jamais facile ce genre de termes

2020-02-03 08:31 UTC, forresst requested changes
J'ai mis un commentaire pour sanitize, tu me donneras ton avis.

J'ai aussi laisser quelques corrections de typo

Encore merci pour ton aide

2020-02-03 08:31 UTC, forresst commented on sections/security/childprocesses.french.md
> +Aussi importants que soient les processus enfants, ils doivent être utilisés avec prudence. Les entrées des utilisateurs qui y sont passées doivent être assainies, voire évitées.
```suggestion
Aussi importants que soient les processus enfants, ils doivent être utilisés avec prudence. Les entrées des utilisateurs qui y sont passées doivent être assainies (NdT *sanitize*), voire évitées. 
```

Ta traduction me parait correcte pour **sanitized**. Je pense que rajouter (NdT *sanitize*) permet d'utiliser le terme anglais pour ceux qui ont l'habitude d'utiliser des fonctions qui portent souvent ce nom.

2020-02-03 08:31 UTC, forresst commented on sections/security/childprocesses.french.md
> +Les dangers d'une entrée non assainie exécutant une logique au niveau du système sont ilimités, allant de l'exécution de code à distance à l'exposition de données système sensibles et aussi de perte
```suggestion
Les dangers d'une entrée non assainie exécutant une logique au niveau du système sont illimités, allant de l'exécution de code à distance à l'exposition de données système sensibles et aussi de perte de données.
```

2020-02-03 08:31 UTC, forresst commented on sections/security/childprocesses.french.md
> +// comme exemple, prenons un script qui prend deux artguments, l'un d'entre eux est une entrée utilisateur non assainie
```suggestion
// comme exemple, prenons un script qui prend deux arguments, l'un d'entre eux est une entrée utilisateur non assainie
```

2020-02-03 08:31 UTC, forresst commented on sections/security/childprocesses.french.md
> +// vous auriez une suprise indésirable
```suggestion
// vous auriez une surprise indésirable
```

2020-02-03 08:31 UTC, forresst commented on sections/security/childprocesses.french.md
> +Extrait de la [documentation](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) Node.js :
```suggestion
Extrait de la [documentation](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) Node.js sur les processus enfant :
```

2020-02-03 21:27 UTC, MrYamous commented on sections/security/childprocesses.french.md
> +Extrait de la [documentation](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) Node.js :
Du coup ici j'aurais plutôt mis enfant au pluriel, comme dans la première phrase : "Aussi importants que soient les processus enfants"
Qu'en penses-tu ?

2020-02-04 07:21 UTC, forresst commented on sections/security/childprocesses.french.md
> +Extrait de la [documentation](https://nodejs.org/dist/latest-v8.x/docs/api/child_process.html#child_process_child_process_exec_command_options_callback) Node.js :
Oui ça me va !

2020-02-04 07:22 UTC, merged